# Generated by Django 3.2.8 on 2022-05-17 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20220516_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='identificador',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
