# Generated by Django 3.2.8 on 2022-05-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20220516_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ManyToManyField(blank=True, to='biblioteca.Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='biblioteca.Categoria'),
        ),
    ]
